In [1]:
# 1. Introduction to Numpy

In [2]:
# Nump is a library developed for python which can handle large, multi-dimensional arrays and matrices. 

In [3]:
# 1.1 Speed comparision between Numpy and Python lists

In [4]:
import time
import numpy as np

size_of_vec = 1000000

def pure_python_version():                                                # This function will return the time for python calculation
    time_python = time.time()                                             # Start time before operation
    my_list1 = range(size_of_vec)                                         # Creating a list with 1000000 values
    my_list2 = range(size_of_vec)
    sum_list = [my_list1[i] + my_list2[i] for i in range(len(my_list1))]  # Calculating the sum
    return time.time() - time_python                                      # Return Current time - start time

def numpy_version():                                                      # This function will return the time for numpy calculation
    time_numpy = time.time()                                              # Start time before operation
    my_arr1 = np.arange(size_of_vec)                                      # Creating a numpy array of 1000000 values
    my_arr2 = np.arange(size_of_vec)
    sum_array = my_arr1 + my_arr2                                         # Calculate the sum
    return time.time() - time_numpy                                       # Return current time - start time


python_time = pure_python_version()                                       # Time taken for Python expression
numpy_time = numpy_version()                                              # Time taken for numpy operation
print("Pure Python version {:0.4f}".format(python_time))
print("Numpy version {:0.4f}".format(numpy_time))
print("Numpy is in this example {:0.4f} times faster!".format(python_time/numpy_time))

Pure Python version 1.4469
Numpy version 0.0156
Numpy is in this example 92.5831 times faster!


In [5]:
# 1.2 Importing the package

In [6]:
# import numpy module and give an alias np,so that we dont have to repeatedly use the longer from of the name.

In [7]:
import numpy as np

In [8]:
# 1.3 Creating numpy arrays

In [9]:
# The key feature of numpy is its N-dimensional arrays or ndarray, having the below specialities.

In [11]:
my_list = [15,16,17,18,19]                      # This is an example of python list
my_list

[15, 16, 17, 18, 19]

In [12]:
type(my_list)                                   # This is a one dimensional arrays type of python objects


list

In [13]:
arr = np.array(my_list)                         # This is a one dimensional array
arr

array([15, 16, 17, 18, 19])

In [14]:
type(arr)

numpy.ndarray

In [15]:
my_mat = [[11,12,13], [22,23,24], [35,36,37], [41,42,43]]                 # Creating a 2D list of lists

In [16]:
mat = np.array(my_mat)                                                   # This is a 2 dimensional array
mat

array([[11, 12, 13],
       [22, 23, 24],
       [35, 36, 37],
       [41, 42, 43]])

In [17]:
type(mat)

numpy.ndarray

In [18]:
# 1.4 Checking the attributes of array

In [19]:
# once you know to create an array, you would be intrested to know the shape, dimensionality and datatype of the elements in the array.

In [20]:
arr.shape                                  # This gives the shape of the aray 

(5,)

In [21]:
mat.shape                                  # This gives ther number of rows and colums of the array

(4, 3)

In [22]:
# Shape function is used to know the resolution of an array

In [23]:
arr.ndim                                   # This is 1 dimensional array

1

In [24]:
mat.ndim                                   # This is a 2 dimensional array or matrix

2

In [25]:
# ndim function is for checking dimension

In [26]:
arr.dtype                                  # The datatype of elements inside array is int32

dtype('int32')

In [27]:
mat.dtype

dtype('int32')

In [28]:
# 1.5 Array Initialization

In [29]:
# Here will learn generating arrays with varying step size

In [30]:
np.arange(11,20)

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [31]:
np.arange(11,20,12)

array([11])

In [32]:
np.zeros(4)

array([0., 0., 0., 0.])

In [33]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [34]:
np.linspace(11,15,19)

array([11.        , 11.22222222, 11.44444444, 11.66666667, 11.88888889,
       12.11111111, 12.33333333, 12.55555556, 12.77777778, 13.        ,
       13.22222222, 13.44444444, 13.66666667, 13.88888889, 14.11111111,
       14.33333333, 14.55555556, 14.77777778, 15.        ])

In [35]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
# 1.6 Array initialization using Random Numbers

In [37]:
# Here we are going to see how to populate array with rabdom number. genrate an array of 5 random numbers.

In [38]:
np.random.rand(5)

array([0.30219122, 0.49466411, 0.18480469, 0.52105275, 0.94380541])

In [39]:
np.random.rand(2,2)

array([[0.4006221 , 0.36577512],
       [0.91193317, 0.14791526]])

In [40]:
np.random.rand(4,4)

array([[0.51192224, 0.06718273, 0.8512867 , 0.69545893],
       [0.14601574, 0.22389623, 0.98621937, 0.19299348],
       [0.41363064, 0.5386703 , 0.47719248, 0.21869073],
       [0.03031016, 0.87323721, 0.87357837, 0.81561665]])

In [41]:
np.random.rand(9).reshape(3,3)

array([[0.83135003, 0.22378391, 0.55686858],
       [0.25192938, 0.57807505, 0.42602005],
       [0.57345446, 0.55542757, 0.88279283]])

In [42]:
# 1.7 Numpy Indexing

In [43]:
# Once we have learned how to create arrays in numpy. 

In [44]:
my_arr = np.arange(0,11)                        # It will return an array from 0 to 10
my_arr  

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
my_arr[10]                                      # It will return element  at index 10

10

In [46]:
# 1.7.1 Array Slicing

In [47]:
# to accescc more than one elemnts of the array use slicing

In [48]:
my_arr[1:5]                                      # It will return all the elements between 1 and 5 excludng 5

array([1, 2, 3, 4])

In [49]:
my_arr[8:]                                       # It will return all elements from index 8 and beyond

array([ 8,  9, 10])

In [50]:
my_arr[:6]                                       # It will return all elements from first index to 5

array([0, 1, 2, 3, 4, 5])

In [51]:
my_arr[0:5] = -5                                 # Numpy arrays are mutable
my_arr

array([-5, -5, -5, -5, -5,  5,  6,  7,  8,  9, 10])

In [52]:
arr_2d = np.array ([[0,1,2], [3,4,5], [6,7,8], [9,10,11]])


In [53]:
arr_2d

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [54]:
arr_2d [0][2]                                    # Elements in 0th row and 2nd coloumn

2

In [55]:
arr_2d [0:2,0:2]                                 # Elements from rows 0 and 1 an columns 0 and 1

array([[0, 1],
       [3, 4]])

In [56]:
arr_2d [:2,1:]                                    # Elements from rows 0 and 1 and columns 1 and 2 

array([[1, 2],
       [4, 5]])

In [57]:
 # 1.7.2 Conditional Indexing is an Array

In [58]:
# first we need to create a boolean array based on an conditional statements using operators for comparison then return filtered elements.

In [59]:
arr_cond = np.arange(0,11)

In [60]:
arr_cond>5                                        # This will return a boolean array

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [61]:
arr_cond[arr_cond > 5]                            # This will return all the elements of an array where elements size > 5

array([ 6,  7,  8,  9, 10])

In [62]:
arr_cond[arr_cond > 5]                            # This is ths same thing without usig another object.

array([ 6,  7,  8,  9, 10])

In [63]:
# 1.8.1 Numpy Broadcasting

In [64]:
# Broadcasting is used to describe how arrays are treated during mathematical oprations. array so that they have compatible sizes.

In [65]:
arr_2d = np.array ([[1,2,3], [5,6,7], [8,9,10], [12,13,14]])             # Creating numpy array
arr_2d

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [12, 13, 14]])

In [66]:
arr_2d.shape

(4, 3)

In [67]:
scaler = 3                                                    # Scaler
arr_1d = np.array([10,10,10])                                 # Array with different shape

In [68]:
arr_1d.shape

(3,)

In [69]:
arr_2d + scaler                                               # Operation with a scaler

array([[ 4,  5,  6],
       [ 8,  9, 10],
       [11, 12, 13],
       [15, 16, 17]])

In [70]:
arr_2d + arr_1d                                               # Operation with a array of different shape

array([[11, 12, 13],
       [15, 16, 17],
       [18, 19, 20],
       [22, 23, 24]])

In [71]:
# 1.8.2 Numpy Mathematical Function

In [72]:
# Function are faster and optimised for large szie arrays.

In [73]:
arr = np.arange(1,11)                                         # Lets forst create a numpy array
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [74]:
arr.min()                                                     # Minimum value of array

1

In [75]:
arr.max()                                                     # Maximum of the array

10

In [76]:
arr.argmin()                                                  # Index position of mininum of array

0

In [77]:
arr.argmax()                                                  # Index position of maximum of array

9

In [78]:
np.sqrt(arr)                                                  # To calculate square root of all element is an array

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [79]:
arr.mean()                                                   # To calculate mean of all the values in an array 

5.5

In [80]:
np.exp(arr)                                                  # To calculate exponential value of each element in an array

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [81]:
# 1.8.3 Array Manipulation

In [82]:
# Here will see some numpy function that can change the structure of an array

In [83]:
arr = np.arange(0,16)                                        # Using reshape wer can change the dimensions of the array

arr_2d =arr.reshape(4,4)

arr_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [84]:
arr_2d.flatten()                                            # Flatten is used to convert a 2d array to 1d array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [85]:
arr_2d.transpose()                                        # transpose is used to convert the rows into coilumns and vice-versa

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [86]:
arr_x = np.array ([[1,2,3,4], [5,6,7,8]])  # Lets create 2 arrays

arr_y = np.array ([[21,22,23,24], [25,26,27,28]])

In [87]:
np.concatenate ((arr_x, arr_y), axis=1)                  # Join 2 array along columns

array([[ 1,  2,  3,  4, 21, 22, 23, 24],
       [ 5,  6,  7,  8, 25, 26, 27, 28]])

In [88]:
arr_z = np.concatenate ((arr_x ,arr_y), axis=0)          # Join 2 arrays along rows

arr_z

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [21, 22, 23, 24],
       [25, 26, 27, 28]])

In [89]:
np.hsplit (arr_z, 2)                                      # It will split the array into 2 equal halves along the columns

[array([[ 1,  2],
        [ 5,  6],
        [21, 22],
        [25, 26]]),
 array([[ 3,  4],
        [ 7,  8],
        [23, 24],
        [27, 28]])]

In [90]:
np.vsplit (arr_z, 2)                                       # It will split array into 2 equal halves along the rows

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[21, 22, 23, 24],
        [25, 26, 27, 28]])]