In [2]:
# 1. create a null vector of size 7 but third and last value as 2

In [3]:
import numpy as np

def generate():
    a = np.zeros(7)
    a[-1] = 2
    a[-2] = 2
    return a

generate()

array([0., 0., 0., 0., 0., 2., 2.])

In [4]:
# 2. Create a vectir of size 9 with values ranging from 0 to 2, both excluded.

In [5]:
import numpy as np

def generate():
    a = np.linspace(0,2,11, endpoint = True)[1:-1]
    return a

generate()

array([0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8])

In [6]:
# 3. convert the first character of each element in a series to uppercase? and return the new series.

In [8]:
import pandas as pd

series = pd.Series(['how', 'to', 'learn', 'data science'])
def generate():
    return series.str.capitalize()

generate()

0             How
1              To
2           Learn
3    Data science
dtype: object

In [9]:
# 4. Given a 3*3 matrix named matrix_fab, from each element of this matrix subtract the mean of that row,name this matrix as matrix

In [11]:
import numpy as np

arr = np.arange(0,9)
matrix_fab = arr.reshape (3,3)
def generate():
    r1Mean = np.mean(matrix_fab[0])
    r2Mean = np.mean(matrix_fab[1])
    r3Mean = np.mean(matrix_fab[2])
    
    matrix_sub = np.array([matrix_fab[0] - r1Mean, matrix_fab[1] - r2Mean, matrix_fab[2] - r3Mean])
    maxArr = np.max(matrix_fab)
    print (matrix_fab)
    print (matrix_sub)
    
    matrix_norm = matrix_sub/maxArr
    print (matrix_norm)
    return None

generate()

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]
[[-0.125  0.     0.125]
 [-0.125  0.     0.125]
 [-0.125  0.     0.125]]


In [12]:
# 5. Create a random vector of size 12, sort it in decreasing order, make 4*3 array using it. (use reshape and sort function)

In [13]:
import numpy as np
def generate():
    
    a = np.random.rand(12)
    a = a[:: -1]
    return a.reshape(4,3)

generate()

array([[0.35068858, 0.3481861 , 0.09960341],
       [0.36994275, 0.20918292, 0.28316995],
       [0.40886528, 0.62879269, 0.82191916],
       [0.58758952, 0.15167308, 0.71534696]])

In [14]:
# 6. Below is python dict data and python list labels. create dataframe df from this dict data which has index as labels.

In [15]:
import numpy as np

data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

import pandas as pd

def generate():
   
    df = pd.DataFrame(data = data, index = labels)
    print (df.info())
    print (df[df.age.isnull()])
    return 

generate()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   animal    10 non-null     object 
 1   age       8 non-null      float64
 2   visits    10 non-null     int64  
 3   priority  10 non-null     object 
dtypes: float64(1), int64(1), object(2)
memory usage: 280.0+ bytes
None
  animal  age  visits priority
d    dog  NaN       3      yes
h    cat  NaN       1      yes


In [16]:
# 7. From the given dataframe df,in the 'animal' column change the 'dog' entries to 'labradoe' change the age in row to to 2.7 and calclate the mean age.

In [17]:
import pandas as pd

data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

def generate():
   
    df = pd.DataFrame(data=data, index=labels)
    print (df)
    
    # print (df.index)
    # print(df[df.animal == 'dog'])
    
    df['animal'] = df.apply(lambda x: 'Labrador' if x.animal == 'dog' else x.animal, 1)
    
    # df = df.replace('dog', 'Labrador')
    # print (df.loc['d','age'])
    
    df.loc['d','age'] = 2.7
    df.loc['h','age'] = 2.7
   
    # print (df.loc['d','age'])
    # Also print df
    
    print (df)
    
    mean_age = df.groupby('animal')
    mean_age = mean_age['age'].mean()
             
    return mean_age   # your variable i.e mean_age

generate()

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no
     animal  age  visits priority
a       cat  2.5       1      yes
b       cat  3.0       3      yes
c     snake  0.5       2       no
d  Labrador  2.7       3      yes
e  Labrador  5.0       2       no
f       cat  2.0       3       no
g     snake  4.5       1       no
h       cat  2.7       1      yes
i  Labrador  7.0       2       no
j  Labrador  3.0       1       no


animal
Labrador    4.425
cat         2.550
snake       2.500
Name: age, dtype: float64

In [18]:
# 8. From the given dataframe get the position where values of two columns match?

In [19]:
import pandas as pd

import numpy as np

df = pd.DataFrame({'fruit1': np.random.choice(['apple', 'orange', 'banana'], 10),
                    'fruit2': np.random.choice(['apple', 'orange', 'banana'], 10)})
def generate():
    
    # your code here
    # print (df)
   
    print (df[(df.fruit1 == df.fruit2)])
    
    # matchStatus = (df.fruit1 == df.fruit2)
    # print (matchStatus[matchStatus == True])
    
    return None

generate()

   fruit1  fruit2
0   apple   apple
1  banana  banana
5  banana  banana
8  banana  banana


In [20]:
# 9. Find the position of numbers that are multiples of 4 from a series? print series and return position.(hint: use argwhere)

In [32]:
import pandas as pd
import numpy as np
series = pd.Series (np.random.randint (1, 10, 7))
def generate():
    # your code here
   
    print (series)
    positions =  (np.argwhere(series%4 ==0))
    return positions 

generate()

0    5
1    1
2    3
3    5
4    5
5    2
6    4
dtype: int32


ValueError: Length of passed values is 1, index implies 7.

In [24]:
# 10. Stack two given vertically and horizontally? print out both.

In [25]:
import pandas as pd

import numpy as np

series1 = pd.Series(range(5))
series2 = pd.Series(list('abcde'))
def generate():
   
    # your code 
    
    hstack = pd.concat([series1, series2]).reset_index()
    vstack = pd.concat([series1, series2], axis=1)
    
    # print out both vertically and horizontally stacked series.
   
    print (hstack)
    print (vstack)
    
    return None

generate()

   index  0
0      0  0
1      1  1
2      2  2
3      3  3
4      4  4
5      0  a
6      1  b
7      2  c
8      3  d
9      4  e
   0  1
0  0  a
1  1  b
2  2  c
3  3  d
4  4  e
