In [1]:
# 1. Fnd all the indices of peaks in a 1D numpy array. peaks are points surrounded by smaller values on both sides.

In [2]:
import numpy as np

n = np.array([2, 7, 1, 3, 7, 1, 2, 6, 0, 1, 3, 7, 6])
def generate():
    
    # your code here
    
    arr = []
    i = 1
    while i < len(n)-1:
        if n[i] > n[i-1] and n[i] > n[i+1]:
            arr.append(i)
        
        i += 1
    print (arr)
    
    return None
generate()

[1, 4, 7, 11]


In [3]:
# 2. Create a 8*8 matrix and fill it with a chessboard pattern as show in the below figure.

In [4]:
import numpy as np
def generate():
    
    # your code
    
    s1 = np.array([0,1]*4)
    s2 = np.array([1,0]*4)
    s = np.vstack((s1,s2))
   
    print (np.array(s.tolist()*4))
    
    return None
generate()

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [7]:
# 3. Generate one hot encoding for a given array.

In [25]:
import numpy as np
import sklearn.preprocessing
np.random.seed(101) 
arr = np.random.randint(1,4, size=6)
def generate(arr):
    # your code here
    print (arr)
    n_values = np.max(arr) + 1
    print (np.eye(n_values)[arr])
    label_binarizer = sklearn.preprocessing.LabelBinarizer()
    label_binarizer.fit(range(max(arr)+1))
    b = label_binarizer.transform(arr)
    print('{0}'.format(b))
    
    return None
generate(arr)

[2 3 2 2 2 1]
[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]]
[[0 0 1 0]
 [0 0 0 1]
 [0 0 1 0]
 [0 0 1 0]
 [0 0 1 0]
 [0 1 0 0]]


In [9]:
# 4. Write python pogram display all the dates foe the month april,1994. also print number of weekdays in april 1994. also check 7th april was a weekdays or not.

In [10]:
import numpy as np
def generate():
    # your code
    a = np.arange('2004-04', '2004-05', dtype='datetime64[D]')
    print (a)
    print (np.busday_count(np.datetime64('2004-04-01'), np.datetime64('2004-04-30')))
    
    return np.is_busday(np.datetime64('2004-04-07'))# True if 7th april 1994 was a weekday.
generate()

['2004-04-01' '2004-04-02' '2004-04-03' '2004-04-04' '2004-04-05'
 '2004-04-06' '2004-04-07' '2004-04-08' '2004-04-09' '2004-04-10'
 '2004-04-11' '2004-04-12' '2004-04-13' '2004-04-14' '2004-04-15'
 '2004-04-16' '2004-04-17' '2004-04-18' '2004-04-19' '2004-04-20'
 '2004-04-21' '2004-04-22' '2004-04-23' '2004-04-24' '2004-04-25'
 '2004-04-26' '2004-04-27' '2004-04-28' '2004-04-29' '2004-04-30']
21


True

In [11]:
# 5. Create a 5*5 array with 1 on the order and 2 inside. now pad this array with a two layer border to get an array named 'nyp'.

In [12]:
import numpy as np
def generate():
    # your code here
    a = [1]*5
    b = [2]*5
    arr = np.vstack((a,b,b,b,a))
    print (arr)
    c = [7]*5
    nyp = np.vstack((c,arr,c))
    print (nyp)
    
    return np.inner(nyp, nyp)#he inner product of "nyp" with itself.
generate()

[[1 1 1 1 1]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [1 1 1 1 1]]
[[7 7 7 7 7]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [1 1 1 1 1]
 [7 7 7 7 7]]


array([[245,  35,  70,  70,  70,  35, 245],
       [ 35,   5,  10,  10,  10,   5,  35],
       [ 70,  10,  20,  20,  20,  10,  70],
       [ 70,  10,  20,  20,  20,  10,  70],
       [ 70,  10,  20,  20,  20,  10,  70],
       [ 35,   5,  10,  10,  10,   5,  35],
       [245,  35,  70,  70,  70,  35, 245]])

In [13]:
# 6. Given dataframe df vwith an integer column 'int' for each value, count the diff back the previous. make this new column 'A'

In [14]:
import pandas as pd
df = pd.DataFrame({'int': [7, 2, 0, 7, 4, 2, 5, 7, 3, 5]})
def generate():
    # your code here
    df1 = df
    #print (df1)
    df1['shift'] = df1['int'].shift(7)
    #print (df1)
    startVal = df1['int'][0]
    df1 = df1.fillna(startVal)
    print (df1)
    df1['A'] = df1['int'] - df1['shift']
    return df1['A']# the new coloumn 'A'
generate()

   int  shift
0    7    7.0
1    2    7.0
2    0    7.0
3    7    7.0
4    4    7.0
5    2    7.0
6    5    7.0
7    7    7.0
8    3    2.0
9    5    0.0


0    0.0
1   -5.0
2   -7.0
3    0.0
4   -3.0
5   -5.0
6   -2.0
7    0.0
8    1.0
9    5.0
Name: A, dtype: float64

In [15]:
# 7. Create the three dataframes based on the given raw data. join data1 and data2 alomg rows to from data_all_rows. merge data_all_row and data3 along the subject_id value to from merge1

In [16]:
import pandas as pd
raw_data_1 = {
        'subject_id': ['1', '2', '3', '4', '5'],
        'first_name': ['Alex', 'Amy', 'Allen', 'Alice', 'Ayoung'], 
        'last_name': ['Anderson', 'Ackerman', 'Ali', 'Aoni', 'Atiches']}

raw_data_2 = {
        'subject_id': ['4', '5', '6', '7', '8'],
        'first_name': ['Billy', 'Brian', 'Bran', 'Bryce', 'Betty'], 
        'last_name': ['Bonder', 'Black', 'Balwner', 'Brice', 'Btisan']}

raw_data_3 = {
        'subject_id': ['1', '2', '3', '4', '5', '7', '8', '9', '10', '11'],
        'test_id': [51, 15, 15, 61, 16, 14, 15, 1, 61, 16]}
def generate():
    # your code
    data1 = pd.DataFrame(raw_data_1)
    data2 = pd.DataFrame(raw_data_2)
    data3 = pd.DataFrame(raw_data_3)
    print (data1)
    print (data2)
    print (data3)
    data_all_row = pd.concat([data1, data2], axis = 0)
    print (data_all_row)
    merge1 = pd.merge(data_all_row, data3, on='subject_id')
    merge2 = pd.merge(data1, data2)
    # print out merge1
    print (merge1)
    # print outmerge2
    print (merge2)
    return None
generate()

  subject_id first_name last_name
0          1       Alex  Anderson
1          2        Amy  Ackerman
2          3      Allen       Ali
3          4      Alice      Aoni
4          5     Ayoung   Atiches
  subject_id first_name last_name
0          4      Billy    Bonder
1          5      Brian     Black
2          6       Bran   Balwner
3          7      Bryce     Brice
4          8      Betty    Btisan
  subject_id  test_id
0          1       51
1          2       15
2          3       15
3          4       61
4          5       16
5          7       14
6          8       15
7          9        1
8         10       61
9         11       16
  subject_id first_name last_name
0          1       Alex  Anderson
1          2        Amy  Ackerman
2          3      Allen       Ali
3          4      Alice      Aoni
4          5     Ayoung   Atiches
0          4      Billy    Bonder
1          5      Brian     Black
2          6       Bran   Balwner
3          7      Bryce     Brice
4         

In [17]:
# 8. Create a dataframe named army from the given data. set the 'origin' colum as the index of the dataframe. find how many total veterans are there.

In [18]:
import pandas as pd
raw_data = {'regiment': ['Nighthawks', 'Nighthawks', 'Nighthawks', 'Nighthawks', 'Dragoons', 'Dragoons', 'Dragoons', 'Dragoons', 'Scouts', 'Scouts', 'Scouts', 'Scouts'],
            'company': ['1st', '1st', '2nd', '2nd', '1st', '1st', '2nd', '2nd','1st', '1st', '2nd', '2nd'],
            'deaths': [523, 52, 25, 616, 43, 234, 523, 62, 62, 73, 37, 35],
            'battles': [5, 42, 2, 2, 4, 7, 8, 3, 4, 7, 8, 9],
            'size': [1045, 957, 1099, 1400, 1592, 1006, 987, 849, 973, 1005, 1099, 1523],
            'veterans': [1, 5, 62, 26, 73, 37, 949, 48, 48, 435, 63, 345],
            'readiness': [1, 2, 3, 3, 2, 1, 2, 3, 2, 1, 2, 3],
            'armored': [1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1],
            'deserters': [4, 24, 31, 2, 3, 4, 24, 31, 2, 3, 2, 3],
            'origin': ['Arizona', 'California', 'Texas', 'Florida', 'Maine', 'Iowa', 'Alaska', 'Washington', 'Oregon', 'Wyoming', 'Louisana', 'Georgia']}
def generate():
    # your code
    df = pd.DataFrame(raw_data)
    print ("================================================================================================")
    print (df)
    print ("================================================================================================")
    df = df.set_index(['origin'])
    print (df)
    print ("================================================================================================")
    print (df['veterans'].sum())
    print ("================================================================================================")
    print (df[(df['deaths'] > 450) | (df['deaths'] < 45)])
    print ("================================================================================================")
    print (df[df["regiment"] != 'Dragoons'])
    print ("================================================================================================")
    print (df.loc[['Texas', 'Arizona']])
    print ("================================================================================================")
    print ((df.loc[['Texas']]).iloc[:,4])

    return # the fifth cell in the row named Texas.¶
generate()

      regiment company  deaths  battles  size  veterans  readiness  armored  \
0   Nighthawks     1st     523        5  1045         1          1        1   
1   Nighthawks     1st      52       42   957         5          2        0   
2   Nighthawks     2nd      25        2  1099        62          3        1   
3   Nighthawks     2nd     616        2  1400        26          3        1   
4     Dragoons     1st      43        4  1592        73          2        0   
5     Dragoons     1st     234        7  1006        37          1        1   
6     Dragoons     2nd     523        8   987       949          2        0   
7     Dragoons     2nd      62        3   849        48          3        1   
8       Scouts     1st      62        4   973        48          2        0   
9       Scouts     1st      73        7  1005       435          1        0   
10      Scouts     2nd      37        8  1099        63          2        1   
11      Scouts     2nd      35        9  1523       

In [20]:
# 9. Filter out and capiltalise all letters of words that contain atleast 2 vowels from a series?

In [21]:
import pandas as pd
series = pd.Series(['Insaid', 'strives', 'for', 'bringing','out','the', 'best','in','you' ])
def generate():
    # your code here
    print (series)
    print ("============================")
    print (series[series.str.lower().str.count(r'[aeiou]') >= 2].str.upper())
    return None
generate()

0      Insaid
1     strives
2         for
3    bringing
4         out
5         the
6        best
7          in
8         you
dtype: object
0      INSAID
1     STRIVES
3    BRINGING
4         OUT
8         YOU
dtype: object


In [22]:
# 10. Create a dataframe from a 4*4 array contaning element from 0 to 15 in a squential order. swap rows third and fourth by creating a generic function two rows.

In [23]:
import numpy as np
import pandas as pd
def swapRows(df, rIndex1, rIndex2):
    temp = df.iloc[rIndex1].copy()
    #print (temp)
    df.iloc[rIndex1] = df.iloc[rIndex2]
    #print (temp)
    df.iloc[rIndex2] = temp
    return df

def generate():
    # Your code here
    a = np.arange(16).reshape(4,4)
    print (a)
    num = pd.DataFrame(a)
    print (num)
    print ("===========================")
    num = swapRows(num, 2,3)
    print (num)
    print ("===========================")
    print (num[::-1])
    # print the modified dataframe
    return None
generate()

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
    0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
    0   1   2   3
0   0   1   2   3
1   4   5   6   7
2  12  13  14  15
3   8   9  10  11
    0   1   2   3
3   8   9  10  11
2  12  13  14  15
1   4   5   6   7
0   0   1   2   3
