In [1]:
# 1. From a 1D array containing elements from -2 to 10 in arithmatic progression with common diff 1.5, negate all elements are betwn 2 and 7 in place.

In [2]:
import numpy as np
def f(x):
    
    if x > 2 and x < 7:
        return -x
    else:
        return x

def generate():
    
    # your code here
    a = np.arange(-2, 10, 1.5)
    a = np.array([f(item) for item in a])
    
    return a# return modified array
generate()

array([-2. , -0.5,  1. , -2.5, -4. , -5.5,  7. ,  8.5])

In [3]:
# 2. Create random vector of size 7 and replace the maximum value by 2 and minimum by 7. sort this array in reverse order. return the modified vector.

In [4]:
import numpy as np
def generate():
   
    # your code
   
    a = np.random.rand(7)
    a = np.sort(a)
    a [0] = 7
    a [-1] = 2
    a = np.sort(a)
    
    # print (a[::-1])
    
    return a [::-1]    # your array
generate()

array([7.        , 2.        , 0.94044617, 0.89941521, 0.72692307,
       0.55326349, 0.51713113])

In [5]:
# 3. Convert a random 7*2 matrix representing cartesian coordinates to polar coordinates. print out both.

In [6]:
import numpy as np
import math
def cart2pol(x, y):
    
    rho = np.sqrt(x**2 + y**2)
    phi = np.arctan2(y, x)
    return(rho, phi)

def generate():
    
    # your code here
    
    car_crd = np.random.rand(7,2)
   
    print (car_crd)
    pol_crd = np.array([cart2pol(pt[0], pt[1]) for pt in car_crd])
    print (pol_crd)
   
    # print out both matrices
    
    return None
generate()

[[0.47150321 0.43601675]
 [0.0360635  0.1077545 ]
 [0.51393461 0.96211055]
 [0.07094153 0.53692625]
 [0.83792207 0.78712341]
 [0.19761005 0.66483745]
 [0.28792349 0.07406939]]
[[0.64220393 0.7463154 ]
 [0.11362926 1.24783237]
 [1.09077289 1.0801846 ]
 [0.54159255 1.43943193]
 [1.14964197 0.7541485 ]
 [0.69358386 1.28188218]
 [0.29729819 0.25179395]]


In [7]:
# 4. create an numpy array sequence named num_seq when only the starting point, step size and length of sequence i given.

In [8]:
import numpy as np

length = 15
start = 5
step = 2

def generate(start, length, step):
    
    # your code here
    
    num_seq = np.arange(start, start + length*step, step)
    
    return num_seq                  # array created by you, i.e. num_seq
generate(start, length, step)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33])

In [9]:
# 5. make a 3*3 array using a 1d array of evenly spaced numbers ranging from 0 to 9, name it arr1.

In [10]:
import numpy as np
def generate():
    
    # your code here
    arr1 = np.arange(0,9).reshape(3,3)
    
    # print (arr1)
    arr2 = np.transpose(arr1)
    
    # print (arr2)
    arr3 = np.ones((1,3))
    
    # print (arr3)
    arr4 = arr2 - arr3
    
    # print (arr4)
    return arr4          # finally created array i.e arr4
generate()

array([[-1.,  2.,  5.],
       [ 0.,  3.,  6.],
       [ 1.,  4.,  7.]])

In [11]:
# 6. Create a datatimeindex that contains each business day of 2016 and use it. index a series of random numbers.

In [12]:
import pandas as pd
import numpy as np
def generate():
    
    # Your code here
    
    DatetimeIndex = pd.date_range(start='2016-01-01', end='2016-12-31',freq='B')
    bus_2k16 = pd.Series(index =DatetimeIndex, data =np.random.rand(len(DatetimeIndex)))
    
    # print out bus_2k16
    
    print (bus_2k16)
    return None
generate()

2016-01-01    0.275264
2016-01-04    0.787803
2016-01-05    0.084885
2016-01-06    0.253925
2016-01-07    0.975540
                ...   
2016-12-26    0.142792
2016-12-27    0.665147
2016-12-28    0.032554
2016-12-29    0.095045
2016-12-30    0.842743
Freq: B, Length: 261, dtype: float64


In [13]:
# 7. Foe each calender month in dataframe bus_2k16, from previous problem. print out mean of values also find the sum of the values in bus.

In [14]:
import pandas as pd
def generate():
    
    # Your code here
    
    DatetimeIndex = pd.date_range(start='2016-01-01', end='2016-12-31',freq='B')
    bus_2k16 = pd.Series(index =DatetimeIndex, data =np.random.rand(len(DatetimeIndex)))
    
    # print (bus_2k16)
    # print out mean
    
    sundaySum =0
    meanSum = []
    meanAvg = []
    for i in bus_2k16.items():
        
        # print (i)
        
        if i[0].is_month_start:
            
            #print ('Month Start')
            meanSum.append(i[1])
       
        elif i[0].is_month_end:
            
            #print ('Month End')
            meanSum.append(i[1])
            meanAvg.append(sum(meanSum)/len(meanSum))
            meanSum=[]
        
        if i[0].weekday == 6:
            sundaySum += i[1]
    
    print (meanAvg)
    
    print (sundaySum)
    
    # print out sum of the values in bus_2k16 for every Sunday.
    return None
generate()

[0.36323022120614695, 0.543753229416871, 0.5668992028614918, 0.32050981581025356, 0.18873533687430866, 0.4026930673823534, 0.6082008430319239, 0.6038982014063969, 0.5483547966806475, 0.3330408374151126, 0.5802098647529512, 0.38077259004506997]
0


In [15]:
# 8. Given the dataframe df, in the fromto column split each string the underscore delimiter to give a new temp dataframe coeerct values.

In [16]:
import numpy as np
df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN', 'londON_StockhOlm', 
                               'Budapest_PaRis', 'Brussels_londOn'],
              'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
              'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
                   'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )', 
                               '12. Air France', '"Swiss Air"']})
import pandas as pd
def generate():
    
    # write your code here
    
    print (df)
    temp = df
    temp['From'] = temp.apply(lambda x: x['From_To'].split('_')[0].capitalize(), 1)
    temp['To'] = temp.apply(lambda x: x['From_To'].split('_')[1].capitalize(), 1)
    temp.drop(columns =['From_To'], inplace = True)
    
    return temp# your temporary variable i.e temp.
generate()

            From_To  FlightNumber  RecentDelays              Airline
0      LoNDon_paris       10045.0      [23, 47]               KLM(!)
1      MAdrid_miLAN           NaN            []    <Air France> (12)
2  londON_StockhOlm       10065.0  [24, 43, 87]  (British Airways. )
3    Budapest_PaRis           NaN          [13]       12. Air France
4   Brussels_londOn       10085.0      [67, 32]          "Swiss Air"


FlightNumber  RecentDelays              Airline      From         To
0       10045.0      [23, 47]               KLM(!)    London      Paris
1           NaN            []    <Air France> (12)    Madrid      Milan
2       10065.0  [24, 43, 87]  (British Airways. )    London  Stockholm
3           NaN          [13]       12. Air France  Budapest      Paris
4       10085.0      [67, 32]          "Swiss Air"  Brussels     London

In [17]:
# 9. Given a dataframe with 10 columns of real numbers. find that columns label which has the smallest sum? also count the number of unique rows the dataframe has.

In [18]:
import numpy as np
import pandas as pd
df = pd.DataFrame(np.random.random(size=(4, 10)), columns=list('qrstuvwxyz'))

print(df)
def generate():
    
    # your code here
    # print(df.columns)
    
    sumDict = {}
    minSumVal = 0
    minSumCol = ''
    
    for col in df.columns:
        sumDict[col]= sum(df[col])
        
        if minSumVal == 0:
            minSumCol = col
            minSumVal = sum(df[col])
        
        elif minSumVal > sum(df[col]):
            minSumCol = col
            minSumVal = sum(df[col])
    
    print (sumDict)
    print (minSumCol)
    
    # print out that column's label which has the smallest sum
    # Also count the number of unique rows the dataframe has.
    
    print (df.drop_duplicates().count())
    
    return None
generate()

          q         r         s         t         u         v         w  \
0  0.499196  0.908661  0.514070  0.401187  0.050167  0.999217  0.800621   
1  0.138121  0.901661  0.046135  0.997239  0.312960  0.038385  0.135246   
2  0.544466  0.762077  0.458610  0.525641  0.150835  0.182899  0.227953   
3  0.502265  0.129648  0.218449  0.211499  0.721581  0.996324  0.831497   

          x         y         z  
0  0.608009  0.423405  0.986772  
1  0.967952  0.161074  0.268174  
2  0.661249  0.475009  0.240077  
3  0.298656  0.973430  0.060838  
{'q': 1.6840485734380415, 'r': 2.7020455777391015, 's': 1.237263684922505, 't': 2.1355665403251107, 'u': 1.2355432763615481, 'v': 2.216825658403563, 'w': 1.9953170799747988, 'x': 2.535866729687605, 'y': 2.032918704211504, 'z': 1.5558612940637948}
u
q    4
r    4
s    4
t    4
u    4
v    4
w    4
x    4
y    4
z    4
dtype: int64


In [19]:
# 10. Given a dataframe df with a column 'int' of integers.print out the dataframe with filtered out rows which contain the same integer as the low above.

In [21]:
import pandas as pd
df = pd.DataFrame({'int': [1, 2, 2, 3, 4, 5, 5, 5, 6, 7, 7]})
def generate():
    
    # your code here
    print (df)
    
    # Print out the dataframe with filtered out rows which contain the same integer as the row immediately above
    print (df[df['int'] == df['int'].shift()])
    
    # Print out the dataframe after subtracting the mean of all integers from each element
    print (df['int'] - df['int'].mean())
    
    return None
generate()

    int
0     1
1     2
2     2
3     3
4     4
5     5
6     5
7     5
8     6
9     7
10    7
    int
2     2
6     5
7     5
10    7
0    -3.272727
1    -2.272727
2    -2.272727
3    -1.272727
4    -0.272727
5     0.727273
6     0.727273
7     0.727273
8     1.727273
9     2.727273
10    2.727273
Name: int, dtype: float64
